name: Run Automated Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 16.13.2
          cache: npm
      - name: run tests
        run: |
          npm install
          npm run test
